In [9]:
import sys
from torch.utils.data.dataloader import DataLoader
import albumentations as A
from albumentations.pytorch import ToTensorV2
import numpy as np

sys.path.append('/home/dogoulis/WORKSPACE/datasets')
from pytorch_dataset import dataset2

In [2]:
transforms = A.Compose([
        # resize
            A.augmentations.geometric.resize.Resize(256, 256),
        # center crop:
            A.augmentations.crops.transforms.CenterCrop (224,224),
            A.Normalize(),
            ToTensorV2()])   
dataset_train = '/home/dogoulis/WORKSPACE/datasets/CSV/train_10k.csv'
dataset_val =  '/home/dogoulis/WORKSPACE/datasets/CSV/validation_dataset.csv'
train_dataset = dataset2(dataset_train ,transforms[0])
val_dataset = dataset2(dataset_val, transforms[1])
# defining data loaders:
train_dataloader = DataLoader(train_dataset, batch_size=24, shuffle=True)

In [3]:
import pandas as pd

df = pd.read_csv(dataset_train)

len(df.label.values)

10000

In [4]:
train_dataset.__init__(dataset_train, transforms)

In [5]:
img, label = train_dataset.__getitem__(1)

In [6]:
img

tensor([[[-0.0116,  0.0227,  0.0741,  ...,  0.2967,  0.2967,  0.2967],
         [-0.0116,  0.0398,  0.0569,  ...,  0.2967,  0.2796,  0.2796],
         [-0.0629, -0.0116,  0.0398,  ...,  0.2624,  0.1939,  0.2453],
         ...,
         [-1.6042, -1.3130, -1.0219,  ..., -2.0837, -2.0837, -2.0837],
         [-1.2788, -1.2617, -1.1932,  ..., -2.0837, -2.0837, -2.0494],
         [-1.2274, -1.1589, -1.3473,  ..., -2.0665, -2.0837, -2.0837]],

        [[ 0.0826,  0.1176,  0.1527,  ...,  0.3978,  0.3978,  0.3978],
         [ 0.0826,  0.1176,  0.1176,  ...,  0.4153,  0.4153,  0.3978],
         [ 0.0476,  0.1001,  0.1176,  ...,  0.3803,  0.3452,  0.3803],
         ...,
         [-1.4755, -1.2654, -1.0378,  ..., -1.9657, -1.9657, -1.9657],
         [-1.2129, -1.1954, -1.1253,  ..., -1.9657, -1.9657, -1.9482],
         [-1.1779, -1.0903, -1.2654,  ..., -1.9482, -1.9482, -1.9657]],

        [[ 0.2522,  0.2871,  0.3045,  ...,  0.5834,  0.5659,  0.5659],
         [ 0.2522,  0.2871,  0.2871,  ...,  0

In [17]:
for data in tqdm(train_dataloader):
    print(data[0], data[1])

  0%|▏                                                                     | 1/417 [00:02<14:39,  2.11s/it]

tensor([[[[ 0.4508,  0.4508,  0.4508,  ..., -0.1999, -0.1828, -0.1657],
          [ 0.4508,  0.4679,  0.4508,  ..., -0.2171, -0.2171, -0.2171],
          [ 0.4337,  0.4508,  0.4508,  ..., -0.2684, -0.2856, -0.3027],
          ...,
          [-1.6384, -1.6727, -1.6898,  ..., -1.1418, -1.0733, -1.0048],
          [-1.7240, -1.7240, -1.7412,  ..., -1.1589, -1.1075, -1.0562],
          [-1.6898, -1.6898, -1.6727,  ..., -1.1589, -1.1075, -1.0733]],

         [[-0.5476, -0.5476, -0.5476,  ..., -1.1429, -1.1253, -1.1078],
          [-0.5476, -0.5301, -0.5476,  ..., -1.1429, -1.1429, -1.1429],
          [-0.5651, -0.5301, -0.5301,  ..., -1.1604, -1.1779, -1.1954],
          ...,
          [-1.6331, -1.6681, -1.6856,  ..., -1.0553, -0.9853, -0.9328],
          [-1.7206, -1.7206, -1.7381,  ..., -1.0728, -1.0203, -0.9678],
          [-1.7031, -1.6856, -1.6856,  ..., -1.0728, -1.0203, -0.9853]],

         [[-1.2641, -1.2816, -1.2990,  ..., -1.4210, -1.4036, -1.3861],
          [-1.2641, -1.2641, -

  0%|▎                                                                     | 2/417 [00:04<14:38,  2.12s/it]

tensor([[[[ 0.3309,  0.3309,  0.3481,  ..., -0.0458, -0.0801, -0.1143],
          [ 0.3652,  0.3652,  0.3823,  ..., -0.0629, -0.0972, -0.1143],
          [ 0.3652,  0.3823,  0.3823,  ..., -0.0629, -0.0801, -0.0972],
          ...,
          [ 2.0263,  2.0263,  2.0263,  ...,  2.1119,  2.1119,  2.1290],
          [ 2.0605,  2.0605,  2.0605,  ...,  2.1290,  2.1290,  2.1462],
          [ 2.0948,  2.0948,  2.0948,  ...,  2.1462,  2.1462,  2.1633]],

         [[-0.9678, -0.9853, -0.9853,  ..., -1.0028, -1.0378, -1.0728],
          [-0.9503, -0.9678, -0.9678,  ..., -1.0203, -1.0553, -1.0903],
          [-0.9503, -0.9678, -0.9678,  ..., -1.0378, -1.0728, -1.0903],
          ...,
          [ 1.5007,  1.5007,  1.5007,  ...,  1.5882,  1.6057,  1.6232],
          [ 1.5357,  1.5357,  1.5357,  ...,  1.6232,  1.6232,  1.6583],
          [ 1.5707,  1.5707,  1.5707,  ...,  1.6408,  1.6408,  1.6758]],

         [[-0.8110, -0.8284, -0.8284,  ..., -0.7238, -0.7587, -0.7936],
          [-0.7936, -0.8110, -

KeyboardInterrupt: 

In [7]:
from tqdm import tqdm